```bash
export WORKON_HOME='/root/python/enviroment'
VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python3
source /usr/local/bin/virtualenvwrapper.sh
```



卸载python3

```python
rpm -qa|grep python3|xargs rpm -ev --allmatches --nodeps
whereis python3 |xargs rm -frv
解决python2和python3相矛盾的问题

查看默认的python或者pip
cd /usr/bin

grep命令进行查找文件里符合条件的字符串
[root@iZm5e98zphj5y525q4v5k4Z bin]# ls | grep pip
lesspipe.sh
pip2
pip2.7
[root@iZm5e98zphj5y525q4v5k4Z bin]# ls | grep python
python
python2
python2.7
python2.7-config
python2-config
python-config
用yum install python3后
[root@iZm5e98zphj5y525q4v5k4Z bin]# ls | grep python
python
python2
python2.7
python2.7-config
python2-config
python3
python3.6
python3.6m
python-config
[root@iZm5e98zphj5y525q4v5k4Z bin]# whereis python3
python3: /usr/bin/python3.6m /usr/bin/python3 /usr/bin/python3.6 /usr/lib/python3.6 /usr/lib64/python3.6 /usr/include/python3.6m /usr/share/man/man1/python3.1.gz

安装到/usr/bin/python3位置

python3自带pip3，无需额外安装
[root@iZm5e98zphj5y525q4v5k4Z bin]# whereis pip
pip: /usr/bin/pip3.6 /usr/bin/pip2.7 /usr/local/bin/pip3.6 /usr/local/bin/pip
安装位置也是在/usr/bin

解决ModuleNotFoundError: No module named 'pip._internal'
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python3 get-pip.py --force-reinstall
将pip3强制重装
[root@iZm5e98zphj5y525q4v5k4Z bin]# pip --version
pip 21.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

[root@iZm5e98zphj5y525q4v5k4Z bin]# pip install --upgrade pip
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Requirement already satisfied: pip in /usr/local/lib/python3.6/site-packages (21.0.1)
更新pip3，后面还得更新pip，因为pip本身也是一个第三方库，用来管理第三方库的

[root@iZm5e98zphj5y525q4v5k4Z etc]# pip install --upgrade pip
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting pip
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/27/79/8a850fe3496446ff0d584327ae44e7500daf6764ca1a382d2d02789accf7/pip-20.3.4-py2.py3-none-any.whl (1.5MB)
     |████████████████████████████████| 1.5MB 3.6MB/s 
Installing collected packages: pip
  Found existing installation: pip 19.1.1
    Uninstalling pip-19.1.1:
      Successfully uninstalled pip-19.1.1
Successfully installed pip-20.3.4
[root@iZm5e98zphj5y525q4v5k4Z etc]# pip --version
pip 20.3.4 from /usr/lib/python2.7/site-packages/pip (python 2.7)


[root@iZm5e98zphj5y525q4v5k4Z bin]# ls |grep python
python
python2
python2.7
python2.7-config
python2-config
python3
python3.6
python3.6m
python-config
[root@iZm5e98zphj5y525q4v5k4Z bin]# python
Python 2.7.5 (default, Nov 16 2020, 22:23:17) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

使用python命令，进入终端，发现默认版本是python2

```



不要乱删除文件，尤其是依赖库

也不要乱改sort link

[centos7-修改默认python为3 - YF-海纳百川 - 博客园 (cnblogs.com)](https://www.cnblogs.com/yuanfang0903/p/11141685.html)

直接修改配置文件，实际上是改了命令的soft link的位置，改成了/usr/bin/python3

如果你要使用Python3作为python的默认版本，你需要修改一下 bashrc 文件，增加一行alias参数
alias python='/usr/local/bin/python3.7'

由于CentOS 7建议不要动/etc/bashrc文件，而是把用户自定义的配置放入/etc/profile.d/目录中，具体方法为
vi /etc/profile.d/python.sh

输入alias参数 alias python="/usr/local/bin/python3.7"，保存退出
如果非root用户创建的文件需要注意设置权限
chmod 755 /etc/profile.d/python.sh

重启会话使配置生效
source /etc/profile.d/python.sh

```bash
[root@iZm5e98zphj5y525q4v5k4Z etc]# python --version
Python 3.6.8
如果修改了pip的alias，但是没有soucre，这个shell脚本没有被执行alias无法生效

[root@iZm5e98zphj5y525q4v5k4Z bin]# vi /etc/profile.d/python.sh
[root@iZm5e98zphj5y525q4v5k4Z bin]# source /etc/profile.d/python.sh
[root@iZm5e98zphj5y525q4v5k4Z bin]# pip --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
```



[centos7 中python pip3安装报警告提示Try pip3 install --user instead._liwu的博客-CSDN博客](https://blog.csdn.net/weixin_43465312/article/details/105480343)

ARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.



[root@iZm5e98zphj5y525q4v5k4Z bin]# ls -al |grep python3 

先进行al显示，然后再进行字符串匹配



我的脚本的位置

/usr/bin/virtualenvwrapper.sh



安装虚拟环境

```bash
目录结构为/roor/website/env/venv
先进入env
virtualenv --python=/usr/bin/python3 venv
创建名为venv的文件夹
里面和windows下面的一样
也有
(venv) [root@iZm5e98zphj5y525q4v5k4Z venv]# pwd
/root/website/env/venv
(venv) [root@iZm5e98zphj5y525q4v5k4Z venv]# ls
bin  lib  lib64  pyvenv.cfg
进入bin
source activate激活虚拟环境
第一次使用先安装依赖项，然后直接运行windows上写好的文件就好了

```



安装uwsgi出错（需要先在系统安装，然后再虚拟环境中安装，虚拟环境中只有一些基本的依赖项）

报错为

```bash
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ah6bahu3/uwsgi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-yuqtdi19-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ah6bahu3/uwsgi/
```



```bash
首先安装devel
yum install python3-devel -y
然后
[root@iZm5e98zphj5y525q4v5k4Z ~]# pip install uwsgi
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Collecting uwsgi
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/c7/75/45234f7b441c59b1eefd31ba3d1041a7e3c89602af24488e2a22e11e7259/uWSGI-2.0.19.1.tar.gz (803kB)
    100% |████████████████████████████████| 808kB 62.4MB/s 
Installing collected packages: uwsgi
  Running setup.py install for uwsgi ... done
Successfully installed uwsgi-2.0.19.1
```





ERRORS:
?: (urls.E006) The STATIC_URL setting must end with a slash.

在static url后面加上/
[Django中为html页面插入背景图片的问题_伯纳乌的博客-CSDN博客](https://blog.csdn.net/weixin_44467002/article/details/97370770)

背景图片



现在的步骤是

pip freeze -> requirements.txt

将所有的第三方库放到txt文件中，然后用git上传到gitee的远程仓库，在云服务器上clone下来

同时用`pip install -r requirements.txt`下载所有需要用到的第三方库，然后再下载时，碰到了问题

很多库的版本不符合

很可能是pip的版本太低的问题

```bash
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# pip --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# python -m pip install --upgrade pip
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting pip
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 46.5MB/s 
Installing collected packages: pip
Successfully installed pip-21.0.1
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# pip --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 21.0.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

```

还是不行，找不到requirements中需要的版本，干脆把库文件的版本给改掉，改成有的



现在安上了，对settings做出修改



    'SQLite 3.9.0 or later is required (found %s).' % Database.sqlite_version
django.core.exceptions.ImproperlyConfigured: SQLite 3.9.0 or later is required (found 3.7.17).

^C(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# pip install sqlite
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement sqlite
ERROR: No matching distribution found for sqlite
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# sqlite --version
-bash: sqlite: command not found
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# sqlite3 --version
3.7.17 2013-05-20 00:56:22 118a3b35693b134d56ebd780123b7fd6f1497668
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# sqlite --version



版本不够了



现在的操作是将python升级到本机的python的版本，或者是将所有依赖项的版本降低到可以升级的部分（这样是直接修改requirements.txt），但是这样的话，第三方库可以，但是如果是database的库还是绕不过去，所以将服务器的版本升级到和本机的相同



```bash
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# python -m pip install -r requirements.txt 
ERROR: Could not find a version that satisfies the requirement pandas==1.2.0
ERROR: No matching distribution found for pandas==1.2.0
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# alias python
alias python='/usr/bin/python3'
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# alias pip
alias pip='/usr/bin/pip3.6'
```



```bash
卸载python3.6
rpm -qa|grep python3|xargs rpm -ev --allmatches --nodeps
whereis python3 |xargs rm -frv

mkdir ~/src
cd ~/src
wget https://www.python.org/ftp/python/3.8.5/Python-3.8.5.tgz
tar -xvf Python-3.8.5.tgz
-x是解压，-c是打包
-v显示细节
-f显示要打包或者解包的文件夹名称
-C指定输出文件名，

yum -y install gcc gcc-c++ zlib zlib-devel//关键

在某个文件下放置安装的文件
mkdir /usr/local/python38
进入源码目录
cd /root/src/Python-3.8.5
进行编译，安装到python38
./configure --prefix=/usr/local/python38

安装命令
make
make install
或者make && make install
创建soft link
这里就应该看出问题了，因为后面都是ll_env还在虚拟环境中
在该链接的时候python被python2占用
https://blog.csdn.net/u014749862/article/details/54430022
mv /usr/bin/python /usr/bin/python_bak
ln -s /usr/local/python38/bin/python3 /usr/bin/python
更新pip python（指的是python3.8.5）-m pip install -U pip
[root@iZm5e98zphj5y525q4v5k4Z Python-3.8.5]# python --version
Python 3.8.5
[root@iZm5e98zphj5y525q4v5k4Z Python-3.8.5]# pip --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 21.0.1 from /usr/local/python38/lib/python3.8/site-packages/pip (python 3.8)
[root@iZm5e98zphj5y525q4v5k4Z Python-3.8.5]# python --version
Python 3.8.5




ln -s /usr/local/python38/bin/python3 /usr/bin/python3
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# ls -al | grep python
lrwxrwxrwx    1 root root         7 Apr 15 21:04 python -> python2
lrwxrwxrwx    1 root root         9 Apr 15 21:04 python2 -> python2.7
-rwxr-xr-x    1 root root      7144 Nov 17 06:23 python2.7
-rwxr-xr-x    1 root root      1835 Nov 17 06:23 python2.7-config
lrwxrwxrwx    1 root root        16 Apr 15 21:04 python2-config -> python2.7-config
lrwxrwxrwx    1 root root        31 Apr 16 14:38 python3 -> /usr/local/python38/bin/python3
lrwxrwxrwx    1 root root        14 Apr 15 21:04 python-config -> python2-config
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# python3 --version
Python 3.8.5
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# python --version
Python 3.8.5
这里才是真正安装好了
在安装第三方库时
  WARNING: The script pbr is installed in '/usr/local/python38/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script virtualenv-clone is installed in '/usr/local/python38/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

简单
在vim /etc/profile 后面加上
export PYTHON_PATH=/usr/local/python38
export PATH=/usr/local/python38/bin:$PATH
source /etc/profile
不提示了
开始后面的创建虚拟环境



(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# pip --version
-bash: /usr/bin/pip3.6: No such file or directory
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# alias pip
alias pip='/usr/bin/pip3.6'
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# ls -al | grep pip
-rwxr-xr-x.   1 root root      2291 Jul 31  2015 lesspipe.sh
-rwxr-xr-x    1 root root       282 Sep  3  2020 pip
-rwxr-xr-x    1 root root       284 Sep  3  2020 pip2
-rwxr-xr-x    1 root root       288 Sep  3  2020 pip2.7
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# yum install pip3
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
No package pip3 available.
Error: Nothing to do

alias仍然为pip3.6但是之前rm python3.6的时候，pip3也没了
手动安装

(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# yum install python3-pip
还没改过来
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# alias pip
alias pip='/usr/bin/pip3.6'
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# pip --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)
(ll_env) [root@iZm5e98zphj5y525q4v5k4Z bin]# python -m pip install --upgrade pip
WARNING: Running pip install with root privileges is generally not a good idea. Try `__main__.py install --user` instead.
Collecting pip
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 66.1MB/s 
Installing collected packages: pip
Successfully installed pip-21.0.1

退出虚拟环境，重新安装3.8.5
然后创建软连接
[root@iZm5e98zphj5y525q4v5k4Z Python-3.8.5]# cd /usr/bin
(reverse-i-search)`ls': ^C
[root@iZm5e98zphj5y525q4v5k4Z bin]# ls -al |grep python
lrwxrwxrwx    1 root root         7 Apr 15 21:04 python -> python2
lrwxrwxrwx    1 root root         9 Apr 15 21:04 python2 -> python2.7
-rwxr-xr-x    1 root root      7144 Nov 17 06:23 python2.7
-rwxr-xr-x    1 root root      1835 Nov 17 06:23 python2.7-config
lrwxrwxrwx    1 root root        16 Apr 15 21:04 python2-config -> python2.7-config
lrwxrwxrwx    1 root root        31 Apr 16 14:55 python3 -> /usr/local/python38/bin/python3
lrwxrwxrwx    1 root root        14 Apr 15 21:04 python-config -> python2-config
[root@iZm5e98zphj5y525q4v5k4Z bin]# pip --version
-bash: /usr/bin/pip3.6: No such file or directory
安装pip

安装成功
重新进入项目文件

现在在centos上安装虚拟环境
pip install virtualenv
pip install virtualenvwrapper
[root@iZm5e98zphj5y525q4v5k4Z ~]# virtualenv --python=python3.8 eenv
RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.8'

这是因为python3.8没有加入到系统的path里面

修改/etc/profile文件，一开始改成了 export 
PATH=$PATH
所以系统命令都无法使用了，很尴尬
要临时使用一下vim，改回来
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
这样就加入到了系统级的环境变量中

alias python='/usr/local/python38/bin/python3.8'
一个大问题，在更换别名时，之前总是提示没有python38这个文件或者目录，原来38之间还有一个逗点

修改/etc/profile
export PYTHON_PATH=/usr/local/python38
export PATH=$PYTHON_PATH/bin:$PATH

[root@iZm5e98zphj5y525q4v5k4Z bin]# echo $PATH
/usr/local/python38/bin:/usr/local/python38/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/python38/bin:/usr/local/python38/bin

永久修改别名
vim /root/.bashrc
添加别名（python指向的bin文件）
到现在为止，python3.8设置好了

开始虚拟环境

创建虚拟环境
virtualenv --python=python3.8 env
确实是用的python3.8
但是pip还是3.6的
但python3.8的库中没有pip模块
/usr/local/python38/bin/python3.8: No module named pip


还需要升级pip

```



echo/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/python38/bin:/usr/local/python38/bin





```ruby
wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-3.4.3-168.el7.centos.noarch.rpm
wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-metadata-parser-1.1.4-10.el7.x86_64.rpm
wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-utils-1.1.31-54.el7_8.noarch.rpm
wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-plugin-fastestmirror-1.1.31-54.el7_8.noarch.rpm
wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-plugin-protectbase-1.1.31-54.el7_8.noarch.rpm
wget http://mirrors.163.com/centos/7/os/x86_64/Packages/yum-plugin-aliases-1.1.31-54.el7_8.noarch.rpm
rpm -ivh yum-* --nodeps --force
```



现在

```bash
(llenv) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# pip --version
pip 21.0.1 from /root/llenv/lib/python3.8/site-packages/pip (python 3.8)
(llenv) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# python --version
Python 3.8.5
pip和python的版本都对了，但是在安装的时候
python3 -m pip install -r requirements.txt
出现报错
ERROR: Could not find a version that satisfies the requirement autopep8==1.5.4
ERROR: No matching distribution found for autopep8==1.5.4
可能是源的问题
python3 -m pip install -r requirements.txt -i--trusted-host http://pypi.mirrors.ustc.edu.cn/simple/
这时候又提示没有SSL 模块，所以安装这个模块

尝试
yum -y update更新必要的软件
yum -y install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel perl wget zlib* libffi-devel wget  zlib* libffi-devel gcc gcc-c++ //进行安装
wget http://distfiles.macports.org/openssl/openssl-1.1.1d.tar.gz
cd /roor/src进入下载目录，解压
tar -zxvf openssl-1.1.1d.tar.gz
./config  --prefix=/usr/local shared zlib &&make && make install

现在来看看

在pip换源的时候，
python -m pip install -r requirements.txt --trusted-host pypi.douban.com -i http://pypi.douban.com/simple/
-r是从这个文本文件中找模块
--trusted-host后面要加上主机名，而不是域名
-i指定域名

现在显示没有ctypes库
按照同样的安装位置（主要是不想改软链接和一些配置文件）
yum install libffi-devel 
然后重新安装
./configure --prefix=/usr/local/python3 --with-ssl
make && make install
源码文件先生成.o文件，然后再生成可执行文件
然后
make clean清除缓存

在pip的时候，意外发现，那些安装不上的库似乎从来没见过
而且一看requirements.txt，我靠，几十个库，怎么可能？
想到在pycharm终端导出库的时候，可能没有进入虚拟环境
所以重新导出，ok，只有四个库，重新git
linux上安装成功！

现在python pip版本正常，所有第三方库正常
django.core.exceptions.ImproperlyConfigured: SQLite 3.9.0 or later is required (found 3.7.17).
这是因为centos自带的sqlist版本不够了
更新一下
先退出虚拟环境
yum remove sqlite//或者用上面卸载python的方法

wget https://www.sqlite.org/2019/sqlite-autoconf-3270200.tar.gz
tar -zxvf sqlite-autoconf-3270200.tar.gz
cd sqlite-autoconf-3270200
./configure --prefix=/usr/local

make && make install
ln -s /usr/local/bin/sqlite3   /usr/bin/sqlite3
[root@iZm5e98zphj5y525q4v5k4Z bin]# sqlite3 --version
3.35.4 2021-04-02 15:20:15 5d4c65779dab868b285519b19e4cf9d451d50c6048f06f653aa701ec212df45e
echo "/usr/local/lib" > /etc/ld.so.conf.d/sqlite3.conf
export LD_LIBRARY_PATH="/usr/local/lib"
ldconfig
sqlite3 -version
这三个命令决定了虚拟环境中sqlite3的版本和系统的版本是不是匹配的
可以进入并激活虚拟环境，然后import sqlite print（sqlite3.sqlite——version)
进行测试
(again) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# ls
db.sqlite3  learning_log  learning_logs  ll_env  manage.py  requirements.txt  users
(again) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# python
Python 3.6.8 (default, Nov 16 2020, 16:55:22) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> sqlite3.sqlite_version
'3.35.4'
而sqlite是否安装上，决定了python manage.py runserver能不能成
如果上线了，可以用curl domain测试




现在安装上了

系统的版本是升级后的，但是python引用的库是没有更新的版本

[root@iZm5e98zphj5y525q4v5k4Z Python-3.8.5]# python3
Python 3.8.5 (default, Apr 17 2021, 11:22:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> f^H^C
KeyboardInterrupt
>>> print(sqlite3.sqlite_version)
3.7.17

现在要让python引用正确的库
import sys
for line in sys.path:
	print(line)
/usr/local/python38/lib/python38.zip
/usr/local/python38/lib/python3.8
/usr/local/python38/lib/python3.8/lib-dynload
/usr/local/python38/lib/python3.8/site-packages

还是先卸载内置的sqlite，这次安装的时候，不要指定安装位置，选择默认的
wget https://www.sqlite.org/2019/sqlite-autoconf-3270200.tar.gz
tar -zxvf sqlite-autoconf-3270200.tar.gz
cd sqlite-autoconf-3270200
./configure && make && make install
ln -s /usr/local/bin/sqlite3   /usr/bin/sqlite3
export LD_LIBRARY_PATH="/usr/local/lib"#添加到~/.bashrc中
source ~/.bashrc

>>> import sqlite3
>>> print(sqlite3.sqlite_version)
3.35.4
https://blog.csdn.net/weixin_39753511/article/details/109393987
在系统的python中导入的是新版本的sqlite
但是在虚拟环境中
仍然是低版本的，可以看到使用的是第二个path下的模块
>>> print(sqlite3.sqlite_version)
3.7.17
>>> import sys
>>> for line in sys.path:
... 	print(line)
... 

/usr/local/python38/lib/python38.zip
/usr/local/python38/lib/python3.8
/usr/local/python38/lib/python3.8/lib-dynload
/root/a/lib/python3.8/site-packages
>>> print(sqlite3)
<module 'sqlite3' from '/usr/local/python38/lib/python3.8/sqlite3/__init__.py'>

解决方法：
yum install sqlite*
然后重装python，

对于虚拟环境中python无法使用delete和方向键的问题
是因为虚拟环境中缺少python的库
pip install readline即可

修改settings
bebug=false

收集Django静态资源到指定目录下：

项目名/settings.py（项目配置，STATIC_ROOT设置收集静态资源的路径）：

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# 指定收集静态文件的路径 (需要修改/var/...目录的操作权限)
STATIC_ROOT='/var/www/项目名/static'
$ python manage.py collectstatic    # Django收集静态资源文件的命令。会将Django项目中的使用到的静态资源收集到 STATIC_ROOT 指定的路径(包括富文本编辑器涉及到的静态资源)。

没有这个目录？

安装uwsgi（不处理静态资源，交给nginx）

验证是否打开了
在服务器上
curl 127.0.0.1:8000/logs/
[17/Apr/2021 15:43:21] "GET /logs/ HTTP/1.1" 200 3197
自带的服务器上确实显示了内容


自己安装uwsgi（利用rpm包出现了错误，需要用名为mockbulid的用户进行安装）
失败，需要安装python对应版本的devel
pip3 install uwsgi

报错：
ERROR: Command errored out with exit status 1: /usr/bin/python3.8 -u -c ‘import sys, setuptools, tokenize; sys.argv[0] = ‘"’"’/tmp/pip-install-zc4elqg3/uwsgi/setup.py’"’"’; file=’"’"’/tmp/pip-install-zc4elqg3/uwsgi/setup.py’"’"’;f=getattr(tokenize, ‘"’"‘open’"’"’, open)(file);code=f.read().replace(’"’"’\r\n’"’"’, ‘"’"’\n’"’"’);f.close();exec(compile(code, file, ‘"’"‘exec’"’"’))’ install --record /tmp/pip-record-ecy5qo7o/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

解决
python2：yum install python-devel
python3：yum install python3-devel

https://blog.csdn.net/ShyLoneGirl/article/details/83030024
必须是对应python版本的，可以用yum search python38看看，发现没有对应的版本
rpm -ivh python38-3.8.3-3.module_el8.3.0+468+0c52a667.src.rpm
解压官网上下载的python38-devel
先创建用户，因为要进入/root/src目录，所以给予超级用户权限
切换用户时不能指定为/sbin/shell，

安装anoconda
Anaconda3-5.3.1-Linux-x86.sh: /root/anaconda3/pkgs/python-3.7.0-hc3d631a_0/bin/python: /lib/ld-linux.so.2: bad ELF interpreter: No such file or directory
yum install glibc.i686
安装时出现错误的原因
[root@iZm5e98zphj5y525q4v5k4Z src]# conda info

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : /root/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-32
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /root/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda3/envs
                          /root/.conda/envs
               platform : linux-32
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/3.10.0-957.21.3.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
还有一个比较坑的，uname显示x86_64架构，结果只能安装32位版本，安装x86_64即报错，说是arrch架构，吐了

现在conda安装时一直solve environment 的错误
conda在使用前要进入base的环境
conda activate base
conda deactivate
https://blog.csdn.net/weixin_41622348/article/details/100582862

如果没找到包
conda config --add channels 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/' 
conda config --add channels 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/'
conda config --setshow_channel_urls yes
换源试试


错误原因：service nginx start 是centos6.x的命令 ， centos7.x使用 systemctl start nginx
关闭nginx -s quit（保存信息）

4 查看nginx是否启动
[root@admin sbin]# ps -aux | grep nginx






ps命令用于报告当前系统的进程状态。

-a：显示所有终端机下执行的程序，除了阶段作业领导者之外。

a：显示现行终端机下的所有程序，包括其他用户的程序。

u：以用户为主的格式来显示程序状况。

x：显示所有程序，不以终端机来区分。

查看端口的占用情况
list open files 
lsof -i:port_num
[root@iZm5e98zphj5y525q4v5k4Z nginx]# lsof -i:80
COMMAND     PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
AliYunDun   982  root   21u  IPv4  14989      0t0  TCP iZm5e98zphj5y525q4v5k4Z:41268->100.100.30.26:http (ESTABLISHED)
nginx     28911  root    6u  IPv4 829136      0t0  TCP *:http (LISTEN)
nginx     28911  root    7u  IPv6 829137      0t0  TCP *:http (LISTEN)
nginx     28912 nginx    6u  IPv4 829136      0t0  TCP *:http (LISTEN)
nginx     28912 nginx    7u  IPv6 829137      0t0  TCP *:http (LISTEN)


cp在进行复制时，如果为目录需要加上-r选项，和复制操作一样


```





现在想想，为什么python要升级到3.8，因为之前的requirements.txt错了，而且sqlite3也错了

所以必须升级到3.8

然而现在不需要那些多余的库了，即使是在python3.6的环境中也能运行

所以明天使用python3.6进行测试

首先安装python3.6

然后安装虚拟环境

然后按照nginx，uwsgi，sqlite来

如果还不成功，就先学mysql算了

```bash
System check identified 1 issue (0 silenced).
April 17, 2021 - 22:57:17
Django version 3.2, using settings 'learning_log.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C(aaa) [root@iZm5e98zphj5y525q4v5k4Z not_forget]# python
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:33) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

